### ISSUE TITLE
errorLogSizeWarningCustomCheckEnabled Error

### ISSUE THREAD

**Issue by miroslavborecky** [devskio/TYPO3-OhDear-Health-Check#1]
Typo3 v12  has problem with Oh dear extension
 Undefined array key "errorLogSizeWarningCustomCheckEnabled" in /vendor/devskio/typo3_ohdear_health_check/Classes/Checks/PhpErrorLogSize.php line 24

**Comment by michalpodrouzek** [comment]
@miroslavborecky fixed

**Comment by michalpodrouzek** [comment]
fixed
